# Generated by Django 4.2.11 on 2024-03-08 06:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0000_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('municipality', models.CharField(max_length=100)),
                ('settlement', models.CharField(max_length=100)),
                ('hours_of_service', models.CharField(max_length=100)),
                ('supply_zone', models.CharField(max_length=100)),
                ('is_atypical_condition', models.BooleanField()),
            ],
        ),
    ]
