# Generated by Django 4.2.11 on 2024-03-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='identifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
