# Generated by Django 4.2.11 on 2024-03-12 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_settlement_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='day_measured',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
